name: "wafer_defect_classifier"
platform: "onnxruntime_onnx"
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 64, 64 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]
